apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-commissioning-handler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repro
  template:
    metadata:
      labels:
        app: repro
    spec:

      containers:
      - name: main-app
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000

      initContainers:
      - name: datadog
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo "init container running"
        resources: {}

      securityContext: {}

      restartPolicy: Always
